name: formula

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/formula.yaml
      - '*.rb'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/formula.yaml
      - '*.rb'

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        formula:
          - kubectl-external-forward
    runs-on: ${{ matrix.platform }}
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@v3
      - run: brew install --formula ./${{ matrix.formula }}.rb
      - run: brew test ${{ matrix.formula }}
